services:

  db:
    image: postgres:18
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: movies
    ports:
      - "5432:5432"
    volumes:
      - ./script/filmes.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql

volumes:
  postgres_data: